import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import deckyPlugin from '@decky/rollup';

const pkg = JSON.parse(readFileSync(new URL('./package.json', import.meta.url), 'utf8'));

const VIRTUAL_ID = 'virtual:build-info';
const RESOLVED_ID = '\0' + VIRTUAL_ID;

/**
 * Stand-in for the build hash, swapped out once the bundle exists. It has to be
 * exactly as long as the hash it becomes: the sourcemap is already generated by
 * the time we substitute, so a length change would shift every mapping after it.
 */
const HASH_PLACEHOLDER = '0BUILDID0';
const HASH_LENGTH = HASH_PLACEHOLDER.length;

/**
 * Exposes the plugin version, and for dev builds a short hash of everything that
 * gets deployed, as a virtual module. The hash is a deploy marker: if the panel
 * shows the hash you expect, the deck is running the code you just built.
 *
 * It covers the backend as well as the bundle, so that a change to main.py alone
 * still moves it -- rollup never sees that file, so we read it here.
 *
 * The hash is taken over the bundle *including* the placeholder, so it stays a
 * stable function of the source rather than of itself.
 *
 * @returns {import('rollup').Plugin}
 */
function buildInfo() {
    const includeHash = process.env.DECKY_DEV_BUILD === '1';

    return {
        name: 'build-info',

        resolveId(id) {
            return id === VIRTUAL_ID ? RESOLVED_ID : null;
        },

        load(id) {
            if (id !== RESOLVED_ID) return null;

            return [
                `export const VERSION = ${JSON.stringify(pkg.version)};`,
                `export const BUILD_HASH = ${JSON.stringify(includeHash ? HASH_PLACEHOLDER : '')};`
            ].join('\n');
        },

        generateBundle(_options, bundle) {
            if (!includeHash) return;

            const backend = readFileSync(new URL('./main.py', import.meta.url));

            for (const chunk of Object.values(bundle)) {
                if (chunk.type !== 'chunk' || !chunk.code.includes(HASH_PLACEHOLDER)) continue;

                const hash = createHash('sha256')
                    .update(chunk.code)
                    .update(backend)
                    .digest('hex')
                    .slice(0, HASH_LENGTH);

                chunk.code = chunk.code.replaceAll(HASH_PLACEHOLDER, hash);
            }
        }
    };
}

export default deckyPlugin({
    plugins: [buildInfo()]
});
